version: '3.8'

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_container
    ports:
      - "4040:4040" # Spark UI port
    volumes:
      - ./app:/app
